name: Promote Staging to Main

on:
  workflow_run:
    workflows: ["CI - Main"]
    types:
      - completed

jobs:
  promote:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Promote staging - main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git checkout -B main
          git push origin main --force

          echo "âœ” main updated from staging"
