name: Promote Staging → Main

on:
  workflow_run:
    workflows: ["CI - Staging"]
    types:
      - completed

jobs:
  promote:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    # ADICIONADO: Permissão para gravação
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Merge staging into main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch origin
          git checkout main
          git merge origin/staging --no-ff --allow-unrelated-histories -m "Auto-merge staging → main"
          git push origin main