name: Promote Development → Staging

on:
  workflow_run:
    workflows: ["CI - Development"]
    types:
      - completed

jobs:
  promote:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout repo
        # Faz checkout da branch 'development' (a source)
        uses: actions/checkout@v4
        with:
          ref: development # Faz o checkout da source branch

      - name: Overwrite staging branch with development content
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Muda para a branch de destino 'staging' (cria se não existir, mas aponta para o head da development)
          git checkout -B staging
          
          # Força o push do conteúdo local (development) para a branch remota 'staging'
          git push origin staging --force
          
          echo "Branch staging sobrescrita com sucesso a partir de development."