name: Promote Staging → Main

on:
  workflow_run:
    workflows: ["CI - Staging"]
    types:
      - completed

jobs:
  promote:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        # Faz checkout da branch 'staging' (a source)
        uses: actions/checkout@v4
        with:
          ref: staging # Faz o checkout da source branch

      - name: Overwrite main branch with staging content
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Muda para a branch de destino 'main' (aponta para o head da staging)
          git checkout -B main
          
          # Força o push do conteúdo local (staging) para a branch remota 'main'
          git push origin main --force
          
          echo "Branch main sobrescrita com sucesso a partir de staging."